apiVersion: v1
kind: Service

metadata:
  # Nama headless service
  name: mysql

spec:

  # Headless service
  clusterIP: None

  selector:
    app: mysql

  ports:
  - port: 3306

    # Port MySQL
    targetPort: 3306