apiVersion: v1
kind: Pod

metadata:
  name: config-demo-pod

spec:
  containers:
  - name: nginx
    image: nginx

    env:
    - name: APP_OWNER
      value: devops-team

    envFrom:
    - configMapRef:
        name: app-config