apiVersion: v1
kind: Pod

metadata:
  # Nama Pod
  name: nginx-no-toleration

spec:
  containers:
  - name: nginx
    # Image container
    image: nginx
    ports:
    # Port aplikasi
    - containerPort: 80
    resources:
      requests:
        # Minimum CPU
        cpu: "100m"
        # Minimum memory
        memory: "128Mi"
      limits:
        # Maximum CPU
        cpu: "300m"
        # Maximum memory
        memory: "256Mi"