apiVersion: v1
kind: Pod

metadata:
  # Nama frontend Pod
  name: frontend-pod
  labels:
    # Label aplikasi frontend
    app: frontend

spec:

  affinity:
    podAffinity:
      # Rule affinity wajib cocok
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            # Cari Pod dengan label app=backend
            operator: In
            values:
            - backend
        # Pod harus berada pada node yang sama
        topologyKey: kubernetes.io/hostname

  containers:
  - name: frontend
    # Image frontend container
    image: nginx
    ports:
    # Port aplikasi frontend
    - containerPort: 80

    resources:

      requests:
        # Minimum CPU
        cpu: "100m"
        # Minimum memory
        memory: "128Mi"

      limits:
        # Maximum CPU
        cpu: "300m"
        # Maximum memory
        memory: "256Mi"