apiVersion: v1
kind: Service
metadata:
  # Nama Service
  name: laravel-web

spec:
  selector:
    # Cari Pod Laravel
    app: laravel-web
  ports:
  - port: 80
    # Port container Laravel
    targetPort: 8080
    # Port pada node
    nodePort: 30080
  # Expose keluar cluster
  type: NodePort